### ISSUE TITLE
Dynamic Client Registration

### ISSUE THREAD

**Issue by strk** [emanoelxavier/openid2go#11]
Does this library support https://openid.net/specs/openid-connect-registration-1_0.html ?

**Comment by emanoelxavier** [comment]
This spec refers to dynamic client registration, a feature that OIDC providers may support. This package is not related to client registration but to the openid idtokens validation done by relying parties. If your relying party is using a provider that supports dynamic registration and you want to dynamically authenticate clients to your relying party then the extension point openid.ProvidersGetter can be used to register a function that dynamically returns the known clients for a given allowed provider.
