### ISSUE TITLE
Token Introspection checking

### ISSUE THREAD

**Issue by rsoletob** [emanoelxavier/openid2go#12]
Could this library support [Token Introspection](https://tools.ietf.org/html/rfc7662) checking?

**Comment by emanoelxavier** [comment]
This package is specific for id tokens rather than an oauth 2 token. It seems introspection would not be necessary here as id tokens have a well defined data structure (as opposed to just oauth tokens) and already contain the information introspection provides. Is that correct?

**Comment by rsoletob** [comment]
Yes, it is. our problem is when an IDP revokes a token. We use this library to verify if tokens are signed by an authorized identity provider, but in some cases, this tokens are revoked before expiry time is reached. An example, we verify access tokens signed by [keycloak](https://github.com/keycloak/keycloak), because they contains all information that this library needs to verify it, but token could be revocated by keycloak. With Token introspection checking, this problem won't happen. 

So,  if the scope of this library is only id tokens, we will implement it by ourselves.
Thanks for your help!!
