### ISSUE TITLE
Is it stable enough for production?

### ISSUE THREAD

**Issue by universonic** [emanoelxavier/openid2go#13]
Hello, I noticed that there is not a single release for this package, so I wonder if it is stable enough to be used in production.

**Comment by emanoelxavier** [comment]
Hello,
Hi @universonic thanks for demonstrating interest on the project. The extent of tests applied to this package is what is in the repo. I have not used this package in production and I am unaware if someone in the community has.  I planned to add releases to the project once more use cases and at least pre-production/staging uses of the package are known. I would recommend trying it out with your scenarios first on a staging environment and exercise it as part of your service/product automated tests. If you find any issues and can help us making it production ready contributions are very welcome.
