### ISSUE TITLE
Inline reference fails to build without package management

### ISSUE THREAD

**Issue by morgasaurus** [emanoelxavier/openid2go#20]
As of commit 7592291 to your master branch, pure inline references to your repository will result in build failures.

This is because underlying "go get" will retrieve your master branch and the master branch of the go-jose dependency.  However, it appears based on the fix changing 'Json' to 'JSON' of various go-jose type names introduced in 7592291 that you are consuming v2 branch of go-jose.  It looks like go-jose either has not yet or does not plan to merge v2 into its master, and the master branch of go-jose does not have the fix changing 'Json' to 'JSON'.

Therefore, master branch of openid2go is not compatible with master branch of go-jose.

This is not a problem if you actively recommend that consumers use package management.  It is only an issue if you wish consumers to be able to simply inline reference your repository without problems.  I just thought you might not yet be aware of these circumstances.

Thank you for your time, and thank you for providing this useful package.

**Comment by emanoelxavier** [comment]
Hi @morgasaurus I am glad you are finding the package useful and thanks for raising the issue. I did want to update to the new version of the jose package and also enable dependency management but not necessarily enforce it. I believe that if I add versioned imports of jose, i.e.: `import "gopkg.in/square/go-jose.v2"` it will address the issue, allowing simply go get to work, agree?

**Comment by morgasaurus** [comment]
Ah to be honest I did not realize that was an option.  Yes that should work perfectly.  Thanks again!
