### ISSUE TITLE
Doesn't work with a JWT without kid

### ISSUE THREAD

**Issue by totallyunknown** [emanoelxavier/openid2go#3]
If the JWT doesn't contain a **kid** field, the interface is nil and can't be casted to string.

https://github.com/emanoelxavier/openid2go/blob/master/openid/idtokenvalidator.go#L87

Fix could be:

```
	if jt.Header[keyIDJwtHeaderName] == nil {
		return tv.keyGetter.getSigningKey(p.Issuer, "" )
	}
	return tv.keyGetter.getSigningKey(p.Issuer, jt.Header[keyIDJwtHeaderName].(string) )
```

I've tried your code to authenticate against Keycloak 1.9.4

**Comment by emanoelxavier** [comment]
Thanks for surfacing this bug. I am currently traveling for work. I will tackle this issue this weekend.

**Comment by iigorr** [comment]
:+1: Had the same problem with missing 'kid' header. Fix worked. Please merge.

**Comment by emanoelxavier** [comment]
Thanks for finding this bug and suggesting a fix. I have committed the fix along with a unit test case and I am closing the issue.
