### ISSUE TITLE
Google App Engine support

### ISSUE THREAD

**Issue by kujenga** [emanoelxavier/openid2go#9]
Google App Engine requires the use of a custom HTTP client called `urlfetch` [1]. I see here [2] that the "http get" functionality is nicely injected, but I don't see any way for an external package to inject anything else... Am I missing something or is new functionality needed to facilitate this?

[1] https://cloud.google.com/appengine/docs/go/issue-requests
[2] https://github.com/emanoelxavier/openid2go/blob/master/openid/middleware.go#L25-L26

**Comment by kujenga** [comment]
I'm looking into preparing a PR for the necessary functionality, which is a bit more complicated than just making the `httpGetFunc`'s configurable, because App Engine needs to create a new `urlfetch.Client` for every request, so I'm looking at injecting it in a way similar to the `ErrorHandlerFunc`.

**Comment by emanoelxavier** [comment]
You are right, the extension point  is partially there but not fully exposed or implemented yet. Your request requires exposing this extension point so the consumer of the middleware can register the configuration and jwks providers. Yes you will need a new function like ErrorHandler or ProvidersGetter. I dont think you need a new httpGetFunc though, instead you can export the existing httpGetFunc and define two new ones, something like ProviderConfigurationGetter and ProviderJwksGetter that are similar to ProvidersGetter but takes the now exposed HttpGetFunc. On your consumer you can now implement your own version of the HttpGetFunc using the urlfetch.Client.

**Comment by emanoelxavier** [comment]
Since you are planning to send a PR I have assigned the issue to yourself, let me know if you would like me to assign to myself instead.

**Comment by emanoelxavier** [comment]
Closing now that the PR is merged. It would be great if you could add a new integration test very similar to Test_Authenticate_ValidIDToken but using the urlFetch client to demonstrate the new extension point.

**Comment by kujenga** [comment]
I like that idea, though that may require the App Engine SDK to be installed in order for the tests to run, which I don't think is desirable. Perhaps it could be mocked somehow? If I have some time I'll look into it.
